apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-graphql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastify-graphql
  template:
    metadata:
      labels:
        app: fastify-graphql
    spec:
      containers:
      - name: fastify-graphql
        image: my-registry/fastify-graphql:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
